services:
  - type: web
    name: outlast-speedrun-tracker
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn main:app --bind 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: SESSION_SECRET
        generateValue: true
      - key: GITHUB_TOKEN
        sync: false
      - key: GITHUB_REPO_OWNER
        value: GrimAarkan
      - key: GITHUB_REPO_NAME
        value: speedruntracker